name: TriBingo
main: net.trilleo.mc.plugins.tribingo.Main
version: 0.1.0
api-version: 1.21
author: Trilleo

commands:
  tribingo:
    description: Main command for the TriBingo plugin
    usage: /tribingo <subcommand> [args]
    aliases:
      - tb