name: TriBingo
main: net.trilleo.mc.plugins.trihunt.Main
version: ${projectVersion}
api-version: 1.21
author: Trilleo

commands:
  tribingo:
    description: Main command for the TriBingo plugin
    usage: /tribingo <subcommand> [args]
    aliases:
      - tb